version: '3.5'
services:
  db1:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - data1:/var/lib/posgresql/data
    ports:
      - "15432:5432"

  db2:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - data2:/var/lib/posgresql/data
    ports:
      - "25432:5432"

volumes:
    data1:
    data2: