s.db1_dim_exporter:
  type: dsm_kedro_plugin.custom_dataset.dsm_dataset.DsmDataNode
  project_folder_name: Staging
  file_name: db1_dim_exporter
  credentials: dsmlibrary
  
s.db2_dim_exporter:
  type: dsm_kedro_plugin.custom_dataset.dsm_dataset.DsmDataNode
  project_folder_name: Staging
  file_name: db2_dim_exporter
  credentials: dsmlibrary