################################################################################
####    Don't Edit!! : This file is generated by dsm_kedro_template only.   ####
################################################################################


from kedro.pipeline import Pipeline, node, pipeline
from .nodes import pass_data

def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(
        [
            node(
                func=pass_data,
                inputs=["sql.sys1_myapp_order"],
                outputs="l.sys1_myapp_order",
                name="l.sys1_myapp_order_node",
            ),
            node(
                func=pass_data,
                inputs=["sql.sys1_myapp_orderitem"],
                outputs="l.sys1_myapp_orderitem",
                name="l.sys1_myapp_orderitem_node",
            ),
            node(
                func=pass_data,
                inputs=["sql.sys1_myapp_item"],
                outputs="l.sys1_myapp_item",
                name="l.sys1_myapp_item_node",
            ),
            node(
                func=pass_data,
                inputs=["sql.sys1_myapp_payment"],
                outputs="l.sys1_myapp_payment",
                name="l.sys1_myapp_payment_node",
            ),
            node(
                func=pass_data,
                inputs=["sql.sys2_myapp_order"],
                outputs="l.sys2_myapp_order",
                name="l.sys2_myapp_order_node",
            ),
            node(
                func=pass_data,
                inputs=["sql.sys2_myapp_orderitem"],
                outputs="l.sys2_myapp_orderitem",
                name="l.sys2_myapp_orderitem_node",
            ),
            node(
                func=pass_data,
                inputs=["sql.sys2_myapp_product"],
                outputs="l.sys2_myapp_product",
                name="l.sys2_myapp_product_node",
            ),
            node(
                func=pass_data,
                inputs=["sql.sys2_myapp_payment"],
                outputs="l.sys2_myapp_payment",
                name="l.sys2_myapp_payment_node",
            ),
            
        ]
    )