################################################################################
####    Don't Edit!! : This file is generated by dsm_kedro_template only.   ####
################################################################################


from kedro.pipeline import Pipeline, node, pipeline
from .nodes import pass_data

def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(
        [
            node(
                func=pass_data,
                inputs=["SQLDataNode___system01___myapp_order"],
                outputs="landing___system01___myapp_order",
                name="landing___system01___myapp_order___node",
            ),
            node(
                func=pass_data,
                inputs=["SQLDataNode___system01___myapp_orderitem"],
                outputs="landing___system01___myapp_orderitem",
                name="landing___system01___myapp_orderitem___node",
            ),
            node(
                func=pass_data,
                inputs=["SQLDataNode___system01___myapp_item"],
                outputs="landing___system01___myapp_item",
                name="landing___system01___myapp_item___node",
            ),
            node(
                func=pass_data,
                inputs=["SQLDataNode___system01___myapp_payment"],
                outputs="landing___system01___myapp_payment",
                name="landing___system01___myapp_payment___node",
            ),
            node(
                func=pass_data,
                inputs=["SQLDataNode___system02___myapp_order"],
                outputs="landing___system02___myapp_order",
                name="landing___system02___myapp_order___node",
            ),
            node(
                func=pass_data,
                inputs=["SQLDataNode___system02___myapp_orderitem"],
                outputs="landing___system02___myapp_orderitem",
                name="landing___system02___myapp_orderitem___node",
            ),
            node(
                func=pass_data,
                inputs=["SQLDataNode___system02___myapp_product"],
                outputs="landing___system02___myapp_product",
                name="landing___system02___myapp_product___node",
            ),
            node(
                func=pass_data,
                inputs=["SQLDataNode___system02___myapp_payment"],
                outputs="landing___system02___myapp_payment",
                name="landing___system02___myapp_payment___node",
            ),
            
        ]
    )