################################################################################
####    Don't Edit!! : This file is generated by dsm_kedro_template only.   ####
################################################################################


from kedro.pipeline import Pipeline, node, pipeline
from .nodes import pass_data

def create_pipeline(**kwargs) -> Pipeline:
    return pipeline([])