ckan_parameter:
  url_ckan: localhost
  api_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njk4OTU1NDYsImp0aSI6IjVJV2NJRXRFSldkcUNZV0ZGVkxKTjdCZHRtSC1qWV9YLUdUN1djT05pd1VpWC1WZ2hfeVJzV0FZR1ZTVzM0cWV5NERpTmJQb0owV1VweDJFIn0.X4Kr-S6_CperfVUSCb8Dnd0-8pzAAmhhiNVAaB3yhPU